[package]
name = "sql"
version = "0.1.0"
edition = "2021"

[dependencies]
proptest = "1.0.0"
serde = "1.0"
serde_json = "1.0"
uuid = {version = "1.10", features = ["v4"]}

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "run_loop"
harness = false
